### PR TITLE
Change of health check logic in proxy. In case of error failed instan…

### PR DESCRIPTION
**Pull request by WoZ**
…ce will be dropped from the ring, not only on ECONNREFUSED error. Fixes statsd/statsd#664

### CODE REVIEW

**Comment by BlueHatbRit** [comment]
Hi @WoZ, at first glance this looks good but I've not had a chance to get a setup to test this just yet so I'll do that over the next day or so and will get back to you with any issues I find.

If anyone else is able to also give this a run to confirm it's working properly then that would be great and would give some more confidence as there don't seem to have tests around the proxy yet.

**Comment by jack-walters** [comment]
@WoZ  thanks. It's working fine.
When connection between statsd-proxy and statsd instance **statsd-c1-1** failed I watched next activity in statsd-proxy log:
```11 Mar 12:00:24 - WARNING: [24451] Removing node c1-1.am.hwtool.priv:8125 from the ring.```
And metrics were sent to the **statsd-c1-2** instance. 
When connection with **statsd-c1-1** has been restored, proxy send metrics to the **statsd-c1-1**
Log:
```11 Mar 12:02:31 - WARNING: [24451] Adding node c1-1.am.hwtool.priv:8125 to the ring.```

**Comment by BlueHatbRit** [comment]
Thanks for testing that @jack-walters, I've set aside some time this evening to test this so I'll confirm that as well. Looks like this will be good to merge though assuming ntohing else is uncovered.

**Comment by WoZ** [comment]
@BlueHatbRit Hello! Did you have a time to check?

We're leaving in production for a 5 days with this patch)

**Comment by BlueHatbRit** [comment]
Hi, sorry for the delay, I've just tested it out and it seems to work well. Thanks so much for the contribution 😁

**Pull request merged**
