### PR TITLE
Add taggs support for graphite backend

### PR DESCRIPTION
**Pull request by yuriyzinchenko**

### CODE REVIEW

**Comment by DanCech** [comment]
This appears to be a modified version of #697, can you explain what it does differently?

**Comment by yuriyzinchenko** [comment]
Hi @DanCech. It seems that metrics transformation works not correct in #697 .
Example
`
var metric = "namespace.metric:1|c|#tag1:val1,tag2:val2,tag3:val3,tag4:val4";
let bits = metric.toString().split("#");
let tags = null;
if (bits.length > 1) {
  tags = bits[1];
}
bits = bits[0].split(":");
let key = bits.shift();
if (tags) {
  key += ";" + tags.replace(",", ";").replace(":", "=");
}
`
Result must be `namespace.metric;tag1=val1;tag2=val2;tag3=va3;tag4=val4` but will be `namespace.metric;tag1=val1;tag2:val2,tag3:val3,tag4:val4`. Not all tags parts are transformed correctly.
In this PR code for metrics transformation works as expected
Example
`
var metric = "namespace.metric:1|c|#tag1:val1,tag2:val2,tag3:val3,tag4:val4";
let bits = metric.toString().split("|#");
let tags = null;
if (bits.length > 1) {
  tags = bits[1];
}
bits = bits[0].split(":");
let key = bits.shift();
if (tags) {
  key += ";" + tags.split(",").join(";").split(":").join("=");
}
`
Result will be `namespace.metric;tag1=val1;tag2=val2;tag3=val3;tag4=val4`
Correct me if I'm wrong

**Comment by DanCech** [comment]
Aha, I see there is a bug in #697 since `replace` in javascript is not global by default.  I'll updtae the original PR with a fix.

On a side note I'd recommend commenting on the original PR or at least referencing it rather than copying and modifying the code without any attribution.

**Comment by yuriyzinchenko** [comment]
:handshake:  No problem. I'll close this PR

**Pull request closed without merging**
